# Generated by Django 3.1 on 2020-08-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200819_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_vote', to='posts.comment'),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='vote_type',
            field=models.IntegerField(choices=[(1, 'Upvote'), (0, 'Downvote')]),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='vote_type',
            field=models.IntegerField(choices=[(1, 'Upvote'), (0, 'Downvote')]),
        ),
    ]
