# Generated by Django 3.1 on 2020-08-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200819_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='vote_type',
            field=models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')]),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='vote_type',
            field=models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')]),
        ),
    ]
