# Generated by Django 3.1 on 2020-08-20 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200820_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_vote', to='posts.post'),
        ),
    ]
